### ISSUE TITLE
MySQL Errors

### ISSUE THREAD

**Issue by Captainthrills** [bob7l/HawkReloaded#53]
Being spammed on every loggable interaction. Running HawkEye-dev Build 66
Server: KCauldron 1.7.10 / tested against Spigot/Bukkit 1.7.10 as well

>[19:20:10 WARN]: [HawkEye] No operations allowed after connection closed.Connection was implicitly closed by the driver.
[19:20:10 WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.Connection was implicitly closed by the driver.
[19:20:10 WARN]:        at sun.reflect.GeneratedConstructorAccessor239.newInstance(Unknown Source)
[19:20:10 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[19:20:10 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
[19:20:10 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[19:20:10 WARN]:        at com.mysql.jdbc.Util.getInstance(Util.java:382)
[19:20:10 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
[19:20:10 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
[19:20:10 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
[19:20:10 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
[19:20:10 WARN]:        at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1213)
[19:20:10 WARN]:        at com.mysql.jdbc.ConnectionImpl.getMutex(ConnectionImpl.java:3101)
[19:20:10 WARN]:        at com.mysql.jdbc.ConnectionImpl.setAutoCommit(ConnectionImpl.java:4975)
[19:20:10 WARN]:        at uk.co.oliwali.HawkEye.database.JDCConnection.setAutoCommit(JDCConnection.java:249)
[19:20:10 WARN]:        at uk.co.oliwali.HawkEye.database.DataManager.run(DataManager.java:391)
[19:20:10 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
[19:20:10 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[19:20:10 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
[19:20:10 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
[19:20:10 WARN]:        at java.lang.Thread.run(Thread.java:745)
[19:20:10 WARN]: Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

>The last packet successfully received from the server was 832,229 milliseconds ago.  The last packet sent successfully to the server was 0 milliseconds ago.
[19:20:10 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[19:20:10 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
[19:20:10 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[19:20:10 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
[19:20:10 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[19:20:10 WARN]:        at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1116)
[19:20:10 WARN]:        at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3082)
[19:20:10 WARN]:        at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:2968)
[19:20:10 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3516)
[19:20:10 WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
[19:20:10 WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
[19:20:10 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2620)
[19:20:10 WARN]:        at com.mysql.jdbc.ConnectionImpl.setAutoCommit(ConnectionImpl.java:5022)
[19:20:10 WARN]:        ... 7 more
[19:20:10 WARN]: Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
[19:20:10 WARN]:        at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:2529)
[19:20:10 WARN]:        at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:2979)
[19:20:10 WARN]:        ... 13 more

**Comment by bob7l** [comment]
That's really weird. Is there any way you could provide me with the entire log? 

Also, a few questions:
1) Does this happen with build #65
2) Does this happen instantly after stating the server, or is there a delay. 

I'm not sure how the connection could be closed without removing it from the connections list first. 

Although there is one thing that could've VERY possibly prevented the removal of the dead connection and that is: https://github.com/bob7l/HawkReloaded/blob/master/src/uk/co/oliwali/HawkEye/database/JDCConnection.java#L37

As you can see, oliver (Or whomever wrote that piece of code), is attempting to remove a connection from the pool using a non-JDCConnection. 

Try this build out: https://www.dropbox.com/s/7xbm4h4sv3x1liy/HawkReloaded.jar?dl=0
It's from another branch i've been working on for the upcomming serialization overhaul, but also contains the quick fix.

**Comment by bob7l** [comment]
Edit: Yeah i'm more then certain that's the issue, so much that i'm pushing the commit now. My guess is he (He being Oliver) never noticed the bug because he implemented soo many checks before allowing a connection to be used. On commit #66, i removed those checks because it was a fairly large overhead and was simply not needed.

**Comment by Captainthrills** [comment]
Confirmed, that build you gave is running without the console spam now, going to give it 20-30 minutes to make sure.

**Comment by Captainthrills** [comment]
One error down, One left to go

>[22:12:54 WARN]: [HawkEye] Communications link failure

The last packet successfully received from the server was 802,208 milliseconds ago.  The last packet sent successfully to the server was 0 milliseconds ago.
[22:12:54 WARN]: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 802,208 milliseconds ago.  The last packet sent successfully to the server was 0 milliseconds ago.
[22:12:54 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[22:12:54 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
[22:12:54 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[22:12:54 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
[22:12:54 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[22:12:54 WARN]:        at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1116)
[22:12:54 WARN]:        at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3082)
[22:12:54 WARN]:        at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:2968)
[22:12:54 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3516)
[22:12:54 WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
[22:12:54 WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
[22:12:54 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2620)
[22:12:54 WARN]:        at com.mysql.jdbc.ConnectionImpl.setAutoCommit(ConnectionImpl.java:5022)
[22:12:54 WARN]:        at uk.co.oliwali.HawkEye.database.JDCConnection.setAutoCommit(JDCConnection.java:249)
[22:12:54 WARN]:        at uk.co.oliwali.HawkEye.database.DataManager.run(DataManager.java:391)
[22:12:54 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
[22:12:54 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[22:12:54 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
[22:12:54 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
[22:12:54 WARN]:        at java.lang.Thread.run(Thread.java:745)
[22:12:54 WARN]: Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
[22:12:54 WARN]:        at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:2529)
[22:12:54 WARN]:        at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:2979)
[22:12:54 WARN]:        ... 13 more

**Comment by bob7l** [comment]
Give this build a go: https://www.dropbox.com/s/qhiddxckfh2cnw3/HawkEye.jar?dl=0

This build utilizes HikariCP rather then our poorly implemented connection pooling. 

Also mind the name, i made this one HawkEye.jar while the last one i gave you was HawkReloaded.jar.

**Comment by Captainthrills** [comment]
Working perfectly now, HikariCP also seems to have boosted database interactions a bit as well

**Comment by bob7l** [comment]
Good to hear. Our previous pooling system was just poorly implemented and produced MASSIVE overheads. I attempted to fix some of the overhead but forgot to alter the health monitor thread to insure unused connections were reaped/re-initialized. 

I also recommend you update to build #67 (Or higher) as it contains a lot more overhead fixes (Such as completely disabling auto-commit rather then switching it on/off). 

Thanks for testing! If you find anymore bugs (Big or small) it'd be great if you could report them on here.
