### ISSUE TITLE
MariaDB issue?

### ISSUE THREAD

**Issue by RoboMWM** [bob7l/HawkReloaded#56]
So for whatever reason I can't get Hawkeye to connect to my database, and all I'm getting is it hanging server startup for ~20 seconds until it times out on the connection - with it stating that it had a problem connecting to the database. I'm not sure what the issue is nor where to look, hence my request for a "debug mode" or at least more informative error messages.

As for my issue, I've setup and can access the user account on the same machine via HeidiSQL, and gave it all permissions to its own, fresh database. Version 1.6.2 as per config, compiled from GitHub.

**Comment by bob7l** [comment]
I have build #77 (http://minebuilders.me:8080/job/HawkEye-Reloaded/77/) running on all five of my public servers without any issues atm. My best guess is you may of accidentally messed up your database credentials or your database has some security disallowing HikariCP from establishing initial connections. 

The only debug hawkeye has atm is internal. Internal being the actual insertion of data and tracking of logging. We don't actually debug the connections in any way - BUT you might be able to enable some sort of advanced debugging within our pooling library HikariCP. https://github.com/bob7l/HawkReloaded/blob/master/src/uk/co/oliwali/HawkEye/database/ConnectionManager.java#L25. Although it's hard to say considering HakariCP utilizes JDBC and wouldn't really be able to debug without a massive amount of code which is the same reason we don't bother to log such things.

**Comment by RoboMWM** [comment]
> database has some security disallowing HikariCP from establishing initial connections

Any way I could test that to figure that out? I've double checked the credentials, database is local.

**Comment by bob7l** [comment]
What OS is the database running on? Windows, CentOS, ect?

**Comment by RoboMWM** [comment]
Windows Server 2012 R2

**Comment by bob7l** [comment]
Ahh. I've never used a windows server so i probably can't help you much. If you have the MySQL console you should try to login through commands.

**Comment by RoboMWM** [comment]
I've been using HeidiSQL to access it, tested the account, was able to access the db - not sure if collation would matter or not?

**Comment by RoboMWM** [comment]
Not sure if this is relevant but found this while searching around. http://stackoverflow.com/questions/26885372/hikaricp-mariadb-java-client-configuration-fails

**Comment by bob7l** [comment]
I'm sure it'd throw an exception rather then hanging. The hanging is caused by Hikari awaiting for a successful connection.

**Comment by RoboMWM** [comment]
It does mention this, however:

`2016-03-31 23:50:27 [WARN] using dataSourceClassName and ignoring jdbcUrl`

**Comment by bob7l** [comment]
That's just because i defined all the properties (Including the dataSourceClassName) so the URL is useless. I only included it just in case HikariCP updates and decides to use it over building one from the properties for whatever reason. 

I'll make a quick (Completely untested) build designed strictly for MariaDB just to see if that's the problem.

**Comment by RoboMWM** [comment]
Alright, was taking a quick look because I don't use the default port 3306.

**Comment by bob7l** [comment]
https://www.dropbox.com/s/qhiddxckfh2cnw3/HawkEye.jar?dl=0

That comments out the various tweaks done to the database to speed up queries. 

I've also pushed a commit added exception printing to the mysql startup. I'm not sure exactly why it was left out to begin with.

**Comment by bob7l** [comment]
Oh.. I may have forgotten about the port in the HikariCP lol... Let me check..

**Comment by bob7l** [comment]
Yup, i somehow managed to forget about the port. I guess it automatically defaults to 3306 when no ports are defined. http://minebuilders.me:8080/job/HawkEye-Reloaded/79/

Should hopefully be fixed.

**Comment by RoboMWM** [comment]
Yea, same result, although I get a nice stacktrace now :D 

```
2016-04-01 00:15:38 [WARN] com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Exception during pool initialization: HikariPool-0 - Connection is not available, request timed out after 30001ms.
2016-04-01 00:15:38 [WARN] 	at com.zaxxer.hikari.pool.HikariPool.initializeConnections(HikariPool.java:526)
2016-04-01 00:15:38 [WARN] 	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:136)
2016-04-01 00:15:38 [WARN] 	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:71)
2016-04-01 00:15:38 [WARN] 	at uk.co.oliwali.HawkEye.database.ConnectionManager.<init>(ConnectionManager.java:39)
2016-04-01 00:15:38 [WARN] 	at uk.co.oliwali.HawkEye.database.DataManager.<init>(DataManager.java:44)
2016-04-01 00:15:38 [WARN] 	at uk.co.oliwali.HawkEye.HawkEye.onEnable(HawkEye.java:84)
2016-04-01 00:15:38 [WARN] 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
2016-04-01 00:15:38 [WARN] 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:319)
2016-04-01 00:15:38 [WARN] 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
2016-04-01 00:15:38 [WARN] 	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:357)
2016-04-01 00:15:38 [WARN] 	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:317)
2016-04-01 00:15:38 [WARN] 	at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:411)
2016-04-01 00:15:38 [WARN] 	at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:376)
2016-04-01 00:15:38 [WARN] 	at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:331)
2016-04-01 00:15:38 [WARN] 	at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:273)
2016-04-01 00:15:38 [WARN] 	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:570)
2016-04-01 00:15:38 [WARN] 	at java.lang.Thread.run(Unknown Source)
2016-04-01 00:15:38 [WARN] Caused by: java.sql.SQLTransientConnectionException: HikariPool-0 - Connection is not available, request timed out after 30001ms.
2016-04-01 00:15:38 [WARN] 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:195)
2016-04-01 00:15:38 [WARN] 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:147)
2016-04-01 00:15:38 [WARN] 	at com.zaxxer.hikari.pool.HikariPool.initializeConnections(HikariPool.java:510)
2016-04-01 00:15:38 [WARN] 	... 16 more
2016-04-01 00:15:38 [WARN] Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
2016-04-01 00:15:38 [WARN] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
2016-04-01 00:15:38 [WARN] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
2016-04-01 00:15:38 [WARN] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
2016-04-01 00:15:38 [WARN] 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
2016-04-01 00:15:38 [WARN] 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
2016-04-01 00:15:38 [WARN] 	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:983)
2016-04-01 00:15:38 [WARN] 	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:339)
2016-04-01 00:15:38 [WARN] 	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2252)
2016-04-01 00:15:38 [WARN] 	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2285)
2016-04-01 00:15:38 [WARN] 	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2084)
2016-04-01 00:15:38 [WARN] 	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:795)
2016-04-01 00:15:38 [WARN] 	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44)
2016-04-01 00:15:38 [WARN] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
2016-04-01 00:15:38 [WARN] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
2016-04-01 00:15:38 [WARN] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
2016-04-01 00:15:38 [WARN] 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
2016-04-01 00:15:38 [WARN] 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
2016-04-01 00:15:38 [WARN] 	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:400)
2016-04-01 00:15:38 [WARN] 	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:327)
2016-04-01 00:15:38 [WARN] 	at com.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:422)
2016-04-01 00:15:38 [WARN] 	at com.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:134)
2016-04-01 00:15:38 [WARN] 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:314)
2016-04-01 00:15:38 [WARN] 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:171)
2016-04-01 00:15:38 [WARN] 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:436)
2016-04-01 00:15:38 [WARN] 	at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:65)
2016-04-01 00:15:38 [WARN] 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:567)
2016-04-01 00:15:38 [WARN] 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:560)
2016-04-01 00:15:38 [WARN] 	at java.util.concurrent.FutureTask.run(Unknown Source)
2016-04-01 00:15:38 [WARN] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
2016-04-01 00:15:38 [WARN] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
2016-04-01 00:15:38 [WARN] 	... 1 more
2016-04-01 00:15:38 [WARN] Caused by: java.net.ConnectException: Connection refused: connect
2016-04-01 00:15:38 [WARN] 	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
2016-04-01 00:15:38 [WARN] 	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
2016-04-01 00:15:38 [WARN] 	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
2016-04-01 00:15:38 [WARN] 	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
2016-04-01 00:15:38 [WARN] 	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
2016-04-01 00:15:38 [WARN] 	at java.net.PlainSocketImpl.connect(Unknown Source)
2016-04-01 00:15:38 [WARN] 	at java.net.SocksSocketImpl.connect(Unknown Source)
2016-04-01 00:15:38 [WARN] 	at java.net.Socket.connect(Unknown Source)
2016-04-01 00:15:38 [WARN] 	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:214)
2016-04-01 00:15:38 [WARN] 	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:298)
2016-04-01 00:15:38 [WARN] 	... 24 more

**Comment by RoboMWM** [comment]
Yup, that was it. Yay.

**Comment by bob7l** [comment]
Oh you're using 1.9? I believe they've completely removed data id's. I'm not exactly sure whether or not HawkEye will be able to properly rollback blocks that contain extra data (Such as wool).

**Comment by RoboMWM** [comment]
Afaik they're a long way from accomplishing that. Rollbacks seem to be working as expected, just tested with colored glass panes and wool.
