### ISSUE TITLE
hk search ERROR: NULL

### ISSUE THREAD

**Issue by TheFluffyWalrus** [bob7l/HawkReloaded#74]
When an OP runs the command it works just fine when a staff member with the right perms runs the command it out puts these errors

`07.08 05:48:57 [Server] INFO _Plumface_ issued server command: /hk search r:we
07.08 05:48:57 [Server] ERROR null
07.08 05:48:57 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'hk' in plugin HawkEye v1.7.2
07.08 05:48:57 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
07.08 05:48:57 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) ~[spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
07.08 05:48:57 [Server] INFO at com.massivecraft.massivelag.inject.command.MassiveLagCommandMap.dispatch(MassiveLagCommandMap.java:59) ~[?:?]
07.08 05:48:57 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
07.08 05:48:57 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1351) [spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
07.08 05:48:57 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1186) [spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
07.08 05:48:57 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
07.08 05:48:57 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
07.08 05:48:57 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
07.08 05:48:57 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
07.08 05:48:57 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
07.08 05:48:57 [Server] INFO at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
07.08 05:48:57 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
07.08 05:48:57 [Server] INFO at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
07.08 05:48:57 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
07.08 05:48:57 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
07.08 05:48:57 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
07.08 05:48:57 [Server] INFO Caused by: java.lang.NullPointerException
07.08 05:48:57 [Server] INFO at uk.co.oliwali.HawkEye.SearchParser.<init>(SearchParser.java:150) ~[?:?]
07.08 05:48:57 [Server] INFO at uk.co.oliwali.HawkEye.commands.SearchCommand.execute(SearchCommand.java:35) ~[?:?]
07.08 05:48:57 [Server] INFO at uk.co.oliwali.HawkEye.commands.BaseCommand.execute(BaseCommand.java:23) ~[?:?]
07.08 05:48:57 [Server] INFO at uk.co.oliwali.HawkEye.HawkCommand.onCommand(HawkCommand.java:53) ~[?:?]
07.08 05:48:57 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
07.08 05:48:57 [Server] INFO ... 16 more`

`07.08 05:50:26 [Server] INFO _Plumface_ issued server command: /hawkeye search r:we
07.08 05:50:26 [Server] ERROR null
07.08 05:50:26 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'hawkeye' in plugin HawkEye v1.7.2
07.08 05:50:26 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
07.08 05:50:26 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) ~[spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
07.08 05:50:26 [Server] INFO at com.massivecraft.massivelag.inject.command.MassiveLagCommandMap.dispatch(MassiveLagCommandMap.java:59) ~[?:?]
07.08 05:50:26 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
07.08 05:50:26 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1351) [spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
07.08 05:50:26 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1186) [spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
07.08 05:50:26 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
07.08 05:50:26 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
07.08 05:50:26 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
07.08 05:50:26 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
07.08 05:50:26 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
07.08 05:50:26 [Server] INFO at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
07.08 05:50:26 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
07.08 05:50:26 [Server] INFO at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
07.08 05:50:26 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
07.08 05:50:26 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
07.08 05:50:26 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
07.08 05:50:26 [Server] INFO Caused by: java.lang.NullPointerException
07.08 05:50:26 [Server] INFO at uk.co.oliwali.HawkEye.SearchParser.<init>(SearchParser.java:150) ~[?:?]
07.08 05:50:26 [Server] INFO at uk.co.oliwali.HawkEye.commands.SearchCommand.execute(SearchCommand.java:35) ~[?:?]
07.08 05:50:26 [Server] INFO at uk.co.oliwali.HawkEye.commands.BaseCommand.execute(BaseCommand.java:23) ~[?:?]
07.08 05:50:26 [Server] INFO at uk.co.oliwali.HawkEye.HawkCommand.onCommand(HawkCommand.java:53) ~[?:?]
07.08 05:50:26 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
07.08 05:50:26 [Server] INFO ... 16 more`

**Comment by TheFluffyWalrus** [comment]
Sure does for myself

**Comment by bob7l** [comment]
I don't know. We've never supported "hk search r:we 07.08 05:48:57" type arguments before from what i remember. You need to specify the t argument for the date/time to be applied to the query.
