### ISSUE TITLE
Unknown column 'world' in 'field list'

### ISSUE THREAD

**Issue by chaz393** [bob7l/HawkReloaded#76]
Getting a ton of errors and logs do not work on spigot 1.10. On the latest build from aug 18. It is a MySQL syntax error and no data is logged to the database. This is with a brand new database. The error is 

Unknown column 'world' in 'field list'

**Comment by bob7l** [comment]
I need more info. Provide the following:

- Error logs (Full stacktrace)

- How to reproduce the error

**Comment by StarDan90** [comment]
I'm also having tons of errors with 1.10.2. Here's the full stacktrace:
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'world' in 'field list'
[23:43:45 WARN]: 	at sun.reflect.GeneratedConstructorAccessor141.newInstance(Unknown Source)
[23:43:45 WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[23:43:45 WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[23:43:45 WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
[23:43:45 WARN]: 	at com.mysql.jdbc.Util.getInstance(Util.java:387)
[23:43:45 WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:941)
[23:43:45 WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3870)
[23:43:45 WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3806)
[23:43:45 WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2470)
[23:43:45 WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2617)
[23:43:45 WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2550)
[23:43:45 WARN]: 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
[23:43:45 WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2073)
[23:43:45 WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2009)
[23:43:45 WARN]: 	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5094)
[23:43:45 WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1994)
[23:43:45 WARN]: 	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
[23:43:45 WARN]: 	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
[23:43:45 WARN]: 	at uk.co.oliwali.HawkEye.database.DataManager.getKeyId(DataManager.java:150)
[23:43:45 WARN]: 	at uk.co.oliwali.HawkEye.database.Consumer.run(Consumer.java:85)
[23:43:45 WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:58)
[23:43:45 WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[23:43:45 WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[23:43:45 WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[23:43:45 WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[23:43:45 WARN]: 	at java.lang.Thread.run(Thread.java:745)

The error happens when I do anything logged by Hawkeye on the server, like placing a block, issuing a command...

**Comment by bob7l** [comment]
Alright thanks for the error! 

I hopefully just fixed it with commit https://github.com/bob7l/HawkReloaded/commit/f66d2f1b976060974ddc8cef37b799afb8b52fa6

Respond back with whether or not it's working. 

Thanks for the update.

**Comment by chaz393** [comment]
sorry I completely forgot to respond with my error log. How do I test to see if it is fixed? The last build on the bukkit page was from April; is there a dev build somewhere?

**Comment by bob7l** [comment]
http://minebuilders.me:8080/job/HawkEye-Reloaded/110/
