### ISSUE TITLE
Hawkeye v1.6.0 generated an exception wheile executing task 15

### ISSUE THREAD

**Issue by AquaRex** [bob7l/HawkReloaded#80]
Running on my Craftbukkit Minecraft 1.11.2 server, the plugin is showing up as green on the plugins list but is now functioning normally. This is the error im getting in the server log:

17.32.05 [WARNING] [HawkEye] Plugin HawkEye v1.6.0 generated an exception while executing task 15
17.32.05 java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
17.32.05 	at uk.co.oliwali.HawkEye.Metrics.postPlugin(Metrics.java:375) ~[?:?]
17.32.05 	at uk.co.oliwali.HawkEye.Metrics.access$400(Metrics.java:69) ~[?:?]
17.32.05 	at uk.co.oliwali.HawkEye.Metrics$1.run(Metrics.java:263) ~[?:?]
17.32.05 	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:53) ~[craftbukkit-1.11.2.jar:git-Bukkit-dbf4ecf]
17.32.05 	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [craftbukkit-1.11.2.jar:git-Bukkit-dbf4ecf]
17.32.05 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_121]
17.32.06 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_121]
17.32.06 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]

**Comment by RoboMWM** [comment]
You should title this as "Metrics needs to be updated"

**Comment by bob7l** [comment]
I didn't even know we used Metrics.. Woops.. 

I'll fix it when i get time off. I'm pretty sure Metrics is dead so i'll probably just remove it all.
